configfile: "config.yml"
include: "rules/base.rules"
populate_metadata(config)

include: "rules/reads.rules"
include: "rules/align.rules"
include: "rules/denovo.rules"
include: "rules/varcall.rules"
include: "rules/taxonid.rules"

rule all:
    input:
        rules.all_reads.input,
        rules.all_align.input,
        rules.all_varcall.input,
        rules.all_denovo.input,
        rules.all_taxonid.input,


# This must always be put at the end. It scans all rules and updates their
# resource requests per the config file.
postprocess_rules(workflow, config)
