configfile: "config.yml"

import acanthophis
acanthophis.populate_metadata(config)


include: "rules/base.rules"
include: "rules/reads.rules"
include: "rules/align.rules"
include: "rules/varcall.rules"
include: "rules/multiqc.rules"
include: "rules/kraken.rules"

rule all:
    input:
        rules.reads.input,
        rules.align.input,
        rules.varcall.input,
        rules.multiqc.input,
        rules.all_kraken.input,
