configfile: "config.yml"
include: "rules/base.rules"
populate_metadata(config)

include: "rules/reads.rules"
include: "rules/align.rules"
include: "rules/denovo.rules"
include: "rules/varcall.rules"
include: "rules/kraken.rules"
include: "rules/kaiju.rules"

rule all:
    input:
        rules.reads.input,
        rules.align.input,
        rules.varcall.input,
        rules.denovo.input,
        rules.all_kraken.input,
        rules.all_kaiju.input,


# This must always be put at the end. It scans all rules and updates their
# resource requests per the config file.
postprocess_rules(workflow, config)
