configfile: "config.yml"

import acantophis
acantophis.populate_metadata(config)


include: acantophis.rules.base
include: acantophis.rules.reads
include: acantophis.rules.align
include: acantophis.rules.varcall
include: acantophis.rules.multiqc
include: acantophis.rules.kraken
include: acantophis.rules.variantannotation

rule all:
    input:
        rules.reads.input,
        rules.align.input,
        rules.varcall.input,
        rules.all_multiqc.input,
        rules.all_kraken.input,
        "data/snpEff/db/ancestral/genes.gff",
