#!/bin/bash

qstatres="$(qstat -f -x $1)"

jobstate=$(echo "$qstatres" | grep job_state | cut -f 2 -d = | xargs echo)
case $jobstate in
    F)
        exitstatus=$(echo "$qstatres" | grep Exit_status | cut -f 2 -d = | xargs echo)
        if [ $exitstatus -ne 0 ]
        then
            echo "failed"
        else
            echo "success"
        fi
        ;;
    H | Q | R | E )
        echo running
        ;;
    *)
        echo unknown status "'$jobstate'" >&2
        echo failed
        ;;
esac
